# Generated by Django 5.1.2 on 2024-10-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('dept', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_weeks', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_weekly_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trend_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.IntegerField()),
                ('dept', models.IntegerField()),
                ('date', models.DateField()),
                ('weekly_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_holiday', models.BooleanField()),
            ],
            options={
                'unique_together': {('store', 'dept', 'date')},
            },
        ),
    ]
